"""Initial migration

Revision ID: 91f1b1b53d5c
Revises: 
Create Date: 2026-09-15 13:52:54.234885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91f1b1b53d5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('location_key', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('soil_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('elevation_data', sa.Float(), nullable=True),
    sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_cache_expires_at'), 'analysis_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_analysis_cache_id'), 'analysis_cache', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_cache_location_key'), 'analysis_cache', ['location_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_cache_location_key'), table_name='analysis_cache')
    op.drop_index(op.f('ix_analysis_cache_id'), table_name='analysis_cache')
    op.drop_index(op.f('ix_analysis_cache_expires_at'), table_name='analysis_cache')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
