"""Add ai_summary to AnalysisCache

Revision ID: e3b884abe257
Revises: 91f1b1b53d5c
Create Date: 2026-09-15 18:58:52.016627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b884abe257'
down_revision: Union[str, Sequence[str], None] = '91f1b1b53d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_cache', sa.Column('ai_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_cache', 'ai_summary')
    # ### end Alembic commands ###
